version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: presales_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: presales_db
      MYSQL_USER: presales_user
      MYSQL_PASSWORD: presales_pass
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10